# Notebook 2: PyTorch Fundamentals



## 1. What is PyTorch?

**Explanation:**
PyTorch is an open-source machine learning framework. It provides a way to perform tensor computations with strong GPU acceleration and a system called **Autograd** for automatic differentiation.

**Why is it used in Deep Learning?**
1. **Dynamic Computation Graphs:** Unlike some frameworks, PyTorch builds the graph "on the fly." This makes it easier to debug and allows for variable-length inputs (like different sentence lengths in NLP).
2. **GPU Support:** It can move calculations from the CPU to the GPU, speeding up training by orders of magnitude.
3. **Pythonic Nature:** It feels like natural Python code, making it the favorite for researchers.

## 2. Tensors: The Foundation

**Concept:**
A **Tensor** is the fundamental data structure in PyTorch. It is conceptually the same as a NumPy array but with two critical additions:
1. It can live on a **GPU**.
2. It can track its own **gradients** (slopes) for optimization.

**Tensor vs NumPy Array:**
| Feature | NumPy Array | PyTorch Tensor |
| :--- | :--- | :--- |
| Hardware | CPU only | CPU & GPU |
| Gradients | Manual | Automatic (Autograd) |
| Syntax | Standard | Very similar to NumPy |

In [13]:
%pip install torch

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [14]:
import torch
import numpy as np

t_list = torch.tensor([1, 2, 3])
# From NumPy
np_arr = np.array([4, 5, 6])
t_numpy = torch.from_numpy(np_arr)
# Random Tensors
t_rand = torch.randn(3, 3) # Normal distribution (mean=0, std=1)
t_ones = torch.ones(2, 2)
t_zeros = torch.zeros(2, 2)

print("T_list:", t_list)
print("T_numpy:", t_numpy)
print("T_rand:\n", t_rand)

T_list: tensor([1, 2, 3])
T_numpy: tensor([4, 5, 6])
T_rand:
 tensor([[ 0.0403,  1.0094,  0.4535],
        [-0.6429, -1.0213,  2.1576],
        [ 0.4958, -1.2679,  1.0063]])


## 3. Tensor Shape and Dimensions

**Why it is required:**
The most common error in Deep Learning is the "Dimension Mismatch." If a layer outputs 10 values but the next layer expects 20, the code will crash. Knowing the exact shape of your tensor at every step is mandatory.

In [15]:
# Creating a 3D Tensor (e.g., [Batch, Height, Width])
t = torch.randn(32, 64, 64)

print(f"Dimensions (ndim): {t.ndim}") # 3
print(f"Shape: {t.shape}") # torch.Size([32, 64, 64])
print(f"Data Type (dtype): {t.dtype}") # torch.float32

Dimensions (ndim): 3
Shape: torch.Size([32, 64, 64])
Data Type (dtype): torch.float32


## 4. Indexing and Slicing

**Why it is required:**
We often need to separate data. For example, in a dataset of `[features, label]`, we slice the tensor to get only the features for the model and only the labels for the loss function.

In [16]:
t = torch.randn(4, 4)
print("Original Tensor:\n", t)

# Slicing: First 2 rows, first 2 columns
slice_t = t[0:2, 0:2]
print("\nSliced (2x2):\n", slice_t)

# Indexing: Specific element at row 1, col 2
print("\nElement at [1, 2]:", t[1, 2])

Original Tensor:
 tensor([[ 0.4613,  0.3892,  0.0044, -1.0259],
        [-0.3303,  1.2726, -1.3067, -0.4708],
        [-1.0023,  0.5401,  1.4086,  0.0272],
        [ 0.7536, -0.6638,  1.3535, -0.6268]])

Sliced (2x2):
 tensor([[ 0.4613,  0.3892],
        [-0.3303,  1.2726]])

Element at [1, 2]: tensor(-1.3067)


## 5. Tensor Reshaping

**Why it is required:**
Data often arrives in a format that doesn't match the model. For example, a 2D image (28x28) must be "flattened" into a 1D vector (784) before it can enter a fully connected neural network.

- **`reshape()`**: Changes the shape.
- **`view()`**: A more efficient version of reshape (requires memory to be contiguous).
- **`flatten()`**: Collapses all dimensions into one.

In [17]:
t = torch.arange(12) # [0, 1, ..., 11]
print("Original:", t)

# Reshape to 3x4
print("\nReshape (3x4):\n", t.reshape(3, 4))

# View (2x6)
print("\nView (2x6):\n", t.view(2, 6))

# Flatten a matrix
matrix = torch.randn(2, 3)
print("\nMatrix:\n", matrix)
print("Flattened:\n", matrix.flatten())

Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshape (3x4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

View (2x6):
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

Matrix:
 tensor([[-0.6922, -0.2095, -0.2530],
        [ 0.9711,  1.1623, -2.0582]])
Flattened:
 tensor([-0.6922, -0.2095, -0.2530,  0.9711,  1.1623, -2.0582])


## 6. Tensor Arithmetic and Broadcasting

**Why it is required:**
Neural networks are essentially giant matrix multiplications. 
- **Element-wise:** Standard `+`, `-`, `*` operators.
- **Matrix Multiplication:** Use `@` or `torch.matmul()`. This is the core operation of a neural network layer.
- **Broadcasting:** When PyTorch automatically expands a smaller tensor to match a larger one during a calculation.

In [18]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Element-wise multiply
print("Element-wise *:\n", a * b)

# Matrix Multiplication
m1 = torch.randn(2, 3)
m2 = torch.randn(3, 2)
res = m1 @ m2
print("\nMatrix Multiplication Result:\n", res)

# Broadcasting: Adding a scalar to a vector
print("\nBroadcasting scalar 10:\n", a + 10) 

Element-wise *:
 tensor([ 4, 10, 18])

Matrix Multiplication Result:
 tensor([[-2.5692, -2.9604],
        [-0.8059, -0.1205]])

Broadcasting scalar 10:
 tensor([11, 12, 13])


## 7. Device Management: CPU vs GPU

**Why it is required:**
Calculating gradients for millions of parameters is slow on a CPU. A GPU has thousands of small cores that can do simple math in parallel, making it ideal for Deep Learning.

**Concept:**
You must explicitly move your tensors and models to the device (`cuda` for NVIDIA GPUs).

In [19]:
# Check if GPU is available
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

t = torch.randn(3, 3)
# Move to GPU
t_gpu = t.to(device)
print(f"Tensor is now on: {t_gpu.device}")

Using device: cpu
Tensor is now on: cpu


## 8. Converting NumPy $\leftrightarrow$ PyTorch

**Why it is required:**
Most data processing (Pandas/NumPy) happens on the CPU. Once the data is cleaned, we convert it to PyTorch tensors to move it to the GPU and train.

In [20]:
# NumPy to PyTorch
np_arr = np.array([1, 2, 3])
t_torch = torch.from_numpy(np_arr)

# PyTorch to NumPy
# Important: If tensor has gradients or is on GPU, must .detach().cpu().numpy()
t_grad = torch.randn(3, 3, requires_grad=True).to(device)
np_back = t_grad.detach().cpu().numpy()

print("PyTorch Tensor:\n", t_grad)
print("Back to NumPy:\n", np_back)

PyTorch Tensor:
 tensor([[ 0.1032, -1.3044, -0.3913],
        [-2.1261,  0.4878, -1.5570],
        [ 1.2162, -0.6937, -1.2616]], requires_grad=True)
Back to NumPy:
 [[ 0.10315499 -1.3044293  -0.3912628 ]
 [-2.126054    0.48779458 -1.5569806 ]
 [ 1.2161516  -0.6936769  -1.2616369 ]]


## 9. Autograd: `requires_grad` and `torch.no_grad()`

**Why it is required:**
The "Learning" in Deep Learning happens by calculating the gradient (slope) of the loss function. 
- **`requires_grad=True`**: Tells PyTorch to remember every operation performed on this tensor. This is used for **Weights**.
- **`torch.no_grad()`**: Tells PyTorch to stop tracking. This is used during **Inference (Prediction)** to save memory and speed up the process.

In [21]:
# Gradient Tracking
x = torch.tensor([2.0], requires_grad=True)
y = x**2 + 5 # Function: y = x^2 + 5

# Compute the gradient (dy/dx)
y.backward()

# Derivative of x^2 + 5 is 2x. At x=2, 2(2) = 4.
print(f"Gradient at x=2: {x.grad}")

Gradient at x=2: tensor([4.])
